/**
 * WW2 combat model coefficients. These are model parameters, not historical facts.
 * Historical calibration must be supplied through the calibration boundary before
 * these values are treated as empirically validated.
 */
export const WW2_COMBAT_COEFFICIENTS = Object.freeze({
  baseRate: 0.00035,
  qualityTrainingWeight: 0.25,
  qualityExperienceWeight: 0.20,
  qualityReadinessWeight: 0.20,
  qualityMoraleWeight: 0.20,
  qualityCohesionWeight: 0.15,
  ammunitionBase: 0.45,
  ammunitionWeight: 0.55,
  sustainmentBase: 0.60,
  sustainmentWeight: 0.40,
  wearWeight: 0.40,
  fatigueWeight: 0.45,
  combatCapabilityBase: 0.72,
  combatPowerWeight: 0.28,
  defaultFrontageScaleKm: 0.65,
  minimumEngagedFraction: 0.35,
  densityMin: 0.65,
  densityMax: 1.45,
  directFireRangeKm: 6,
  artilleryRangeKm: 20,
  airRangeKm: 30,
  closeAssaultKm: 3,
  mainEngagementKm: 8,
  approachCommitment: 0.35,
  preparationCommitment: 0.65,
  assaultCommitment: 0.90,
  reserveDefaultFraction: 0.15,
  reserveOrderFraction: 0.65,
  suppressionBase: 0.04,
  suppressionFireWeight: 0.24,
  suppressionLossWeight: 0.20,
  suppressionArtilleryWeight: 0.10,
  disorganizationBase: 0.02,
  disorganizationSuppressionWeight: 0.30,
  disorganizationLossWeight: 0.20,
  disorganizationCommandWeight: 0.04,
  equipmentLossBase: 0.008,
  equipmentLossPersonnelWeight: 0.055,
  equipmentLossCapabilityMin: 0.65,
  ammunitionBaseUse: 0.010,
  ammunitionIntensityWeight: 0.035,
  ammunitionArtilleryWeight: 0.010,
  ammunitionAirWeight: 0.006,
  fuelBaseUse: 0.003,
  fuelIntensityWeight: 0.012,
  fuelArmorWeight: 0.010,
  fuelManeuverWeight: 0.008,
  readinessBaseLoss: 0.008,
  readinessPersonnelLossWeight: 0.20,
  readinessIntensityWeight: 0.025,
  readinessSuppressionWeight: 0.04,
  moraleBaseLoss: 0.004,
  moralePersonnelLossWeight: 0.16,
  moraleIntensityWeight: 0.025,
  moraleSurpriseWeight: 0.03,
  outcomeRepulsed: 0.65,
  outcomeStall: 0.95,
  outcomeLocalGain: 1.35,
  outcomePenetration: 1.35,
  outcomeBreakthrough: 1.75,
  outcomeExploitMobilityGap: 0.08,
  outcomePenetrationDisorganization: 0.10,
  outcomeBreakthroughDisorganization: 0.15,
  outcomeWithdrawalDisorganization: 0.45,
  movementPenetrationKm: 0.5,
  movementLocalGainKm: 0.15,
  movementBreakthroughKm: 2.0,
  movementWithdrawalKm: 1.0,
  movementCounterattackKm: 0.5,
  phasePreparationRangeKm: 12,
  phaseApproachRangeKm: 20,
});

export type WW2CombatCoefficientName = keyof typeof WW2_COMBAT_COEFFICIENTS;
